//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repair_service.DBStorrage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public System.DateTime Date_of_adding { get; set; }
        public System.DateTime Date_of_taskclosing { get; set; }
        public string Equipment_for_repait { get; set; }
        public string Type_of_issue { get; set; }
        public string Description_of_issue { get; set; }
        public string Client_surname { get; set; }
        public string Client_name { get; set; }
        public string Client_phone_number { get; set; }
        public int Task_status { get; set; }
        public int Responsible_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task_status Task_status1 { get; set; }
    }
}
